### ISSUE TITLE
Get rid of get_data in functions?

### ISSUE THREAD

**Issue by arthus701** [AnkitBarik/planetMagFields#3]
Hi @AnkitBarik,
when using the pacakge further, I found that you pass the planet name and data directory to several functions, instead of using the `planet` class. This prevented me from utilizing your package to the fullest, as I wanted to inherit from planet to implement other models (the ones included in [pymagglobal](https://sec23.git-pages.gfz-potsdam.de/korte/pymagglobal/)). It would be much easier for me and probably others that have models based on spherical harmonics, if functions like [`get_Br`](https://github.com/AnkitBarik/planetMagFields/blob/9686b44e9fa3dd87c128cc18e13f7eb43dc1639b/planetmagfields/libbfield.py#L12) and [`plotMagField`](https://github.com/AnkitBarik/planetMagFields/blob/9686b44e9fa3dd87c128cc18e13f7eb43dc1639b/planetmagfields/libbfield.py#L86) could work on instances of `planet` directly.

If you agree, I could help out with a PR.

Cheers,
Arthus

**Comment by AnkitBarik** [comment]
Hi @arthus701 ,

Having the functions act on the class instead of passing the name and directory is indeed a good idea. I wrote the functions first and the class later and forgot to clean it up. :D

However, I don't understand why you want to get rid of `get_data` (as the title suggests) ?

Cheers,
Ankit

**Comment by arthus701** [comment]
Ah yes, I'm sorry. The title is a bit misleading. I meant to get rid of the call to `get_data` in functions like `get_Br`...

**Comment by AnkitBarik** [comment]
Hi @arthus701 ,

This leads to a circular import error: `planet` is trying to import `get_Br` from `libbfield` while `libbfield` is trying to import `planet` at the same time. Have you tested this?

**Comment by arthus701** [comment]
Alright, sure. Let me know if I can assist you in any way.
