### ISSUE TITLE
Installing with anaconda

### ISSUE THREAD

**Issue by MissKLKnowles** [AnkitBarik/planetMagFields#6]
Hi everyone!
This is a really amazing and useful package you have here!
I can't seem to install the package using anaconda, as I always get an error message, and I've exhausted any ways I can think of trying to install the package. To be more specific, I'm using Jupyter notebooks through Anaconda. If you could offer me any guidance or advice, I would really appreciate it!

**Comment by AnkitBarik** [comment]
Hi, thank you for your kind words!
The easiest way is to install using `python3 setup.py install --user` or same with pip: `pip install . --user` both with the Anaconda environment activated. You may have already tried this, in which case, could you post the error message you get?

**Comment by MissKLKnowles** [comment]
Thank you for your quick reply! 
Here is the error:
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by AnkitBarik** [comment]
I tried it just now on a Windows system with Anaconda and was able to reproduce this. I'll take a look at what's going on. In the meantime, an easier way to use the package would be to add the folder to your PYTHONPATH:

`export PYTHONPATH=$PYTHONPATH:/path/to/planetMagFields`

and then you should be able to import it : `from planetmagfields import *`

Let me know if that works.

**Comment by MissKLKnowles** [comment]
I can't seem to get the above to work either.

**Comment by AnkitBarik** [comment]
Hi, I just tried both methods on a Linux machine and they seemed to work.
Could you tell me a bit about which OS you're using?

**Comment by MissKLKnowles** [comment]
Hi, I'm using Windows, (specifically Windows_NT) - I will warn you that I am still fairly new to coding and am therefore still learning, so it could very well be that I am doing something wrong when attempting to install the package (such that I can use it in a Jupyter notebook).

**Comment by AnkitBarik** [comment]
Oh okay Windows. There are two ways of going about it. One is to edit the PYTHONPATH environment variable and include the planetMagFields folder in it. On Windows you can do it using the Control Panel as described here: https://stackoverflow.com/a/7473134

Yet another way of using the package would be at the top where you import stuff, insert the following

```python
import os
import sys
sys.path.append(os.path.join('C:/', 'path', 'to','planetMagFields'))
from planetmagfields import *
```

where C:\path\to\planetMagFields is the full folder path. Let me know if this helps.

**Comment by MissKLKnowles** [comment]
I've managed to finally get it working - thank you all for your patience, guidance and advice!
