### ISSUE TITLE
Add Community guidelines for contributions by third parties

### ISSUE THREAD

**Issue by athulpg007** [AnkitBarik/planetMagFields#9]
Please add a section to the repo readme file on Community guidelines explaining How to: 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. Please see this example here: https://github.com/astropy/astropy?tab=readme-ov-file#contributing-code-documentation-or-feedback

**Comment by AnkitBarik** [comment]
I have added a paragraph in the [README](https://github.com/AnkitBarik/planetMagFields) and the [documentation](https://ankitbarik.github.io/planetMagFields/) , please check if this looks good. Thank you!

**Comment by athulpg007** [comment]
Looks good, thanks.
